#!/usr/bin/sh
alias cats='highlight --style=solarized-dark  --out-format=ansi --tab=4'
alias ls='ls -lhN --color --group-directories-first'
alias grep='grep --color=auto'

# only load if the script exists and i3 is running 
if [ "$(pidof 'i3')" ]; then
    if [ -s "$HOME/.config/i3/script_lock.sh" ]; then
        alias lock_wlaw="sh $HOME/.config/i3/script_lock.sh"
    fi
    if [ -s "$HOME/.config/i3/script_lock_suspend.sh" ]; then
        alias lock_suspend="sh $HOME/.config/i3/script_lock_suspend.sh"
    fi
fi


